-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website_address character varying(20) NOT NULL,
    phone_number character varying(11) NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.employers_verifications
(
    id integer NOT NULL,
    hrms_personel_verification boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.hrms_personels
(
    hrms_personel_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    PRIMARY KEY (hrms_personel_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seeker_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    nationality character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public.job_seekers_verifications
(
    id integer NOT NULL,
    mernis_verification boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(30) NOT NULL,
    password character varying(30) NOT NULL,
    verification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verifications
(
    id integer NOT NULL,
    email_verification boolean,
    PRIMARY KEY (id)
);

ALTER TABLE public.job_seekers_verifications
    ADD FOREIGN KEY (id)
    REFERENCES public.verifications (id)
    NOT VALID;


ALTER TABLE public.employers_verifications
    ADD FOREIGN KEY (id)
    REFERENCES public.verifications (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.hrms_personels
    ADD FOREIGN KEY (hrms_personel_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.verifications
    ADD FOREIGN KEY (id)
    REFERENCES public.users (verification_id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (id)
    REFERENCES public.users (job_position_id)
    NOT VALID;

END;